name: githubster
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  page_transition: ^2.1.0
  dio: ^5.3.3
  bloc: ^8.1.2
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.2
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  url_launcher: ^6.1.14

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway-regular.ttf
          weight: 400
        - asset: assets/fonts/raleway-semibold.ttf
          weight: 600

